version: "3"
services:
  server:
    image: studentdemo
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/Spring?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=Spring
      - MYSQL_USER=aaroe
      - MYSQL_PASSWORD=myPassword

networks:
  springmysql-net: